icons-enabled=no

width=40
horizontal-pad=10
vertical-pad=10
inner-pad=10


[colors]
# background=1e1e2edd
# text=cdd6f4ff
# prompt=bac2deff
# placeholder=7f849cff
# input=cdd6f4ff
# match=89b4faff
# selection=585b70ff
# selection-text=cdd6f4ff
# selection-match=89b4faff
# counter=7f849cff
# border=89b4faff
border=a7c080ff
background=272e33ff
text=d3c6aaff
match=e67e80ff
selection=464e53ff
selection-match=e67e80ff
selection-text=d3c6aaff

